### ISSUE TITLE
Issues (so far)

### ISSUE THREAD

**Issue by xshatter** [battlemines/issueTracker#2]
It seems like around of a quarter of players per game don't get out of the glass box at the start to be able to play

Also, the report system is broken, you can do /report and the options are shown but clicking any of the options doesn't send any reports or exit you out of the report menu.

Lastly (for now), spectating did not work for me most of the time, usually in 1.8 you can press a number twice and it would spectate the person on that number, but nothing seems to happen right now

**Comment by barcedev** [comment]
The spectating and the scatter have been fixed. For now, use https://battlemines.net/report  for reporting players
