### ISSUE TITLE
Not Spawning in And Issue Link Doesn't work

### ISSUE THREAD

**Issue by YourDestinyISIGN** [battlemines/issueTracker#3]
Hello! I am using a Mac OS but I don't think that matters since I'm playing Minecraft. Once and a While you won't drop into the game and clicking the issue link doesn't work. I also found that when spectating there is a massive Player stand in your way. Thx for taking time to read ~YourDestinyIS

**Comment by barcedev** [comment]
We fixed the armor stand, and the scattering is being worked on. Thanks for your report
